from django.core.management.base import BaseCommand
from core.models import Profession


class Command(BaseCommand):
    help = "Precarica solo le professioni nel database"

    def handle(self, *args, **options):
        professions = [
            'Ufficio.1',
            'Ufficio.2',
            'Ufficio.3',
            'Ufficio.4',
            'Ufficio - Preposto.1',
            'Magazzino.1',
            'Magazzino.2',
            'Coordinatore Generale - Preposto.1',
            'Coordinatore Operativo COVA - Preposto.1',
            'Tecnico Specializzato CNP/Gas Free - Preposto solo WE.1',
            'Tecnico Specializzato CNP/Gas Free - Preposto.1',
            'Front Office BO 1 - Preposto.1',
            'Front Office BO2.1',
            'Supporto Front Office ACAM - Lun/Ven (Fine settimana Site Operations Specialist/Tecnico HSE).1',
            'Operatore analisi Gas (Linee e Claus) - Preposto.1',
            'Operatore analisi Gas (Linee e Claus).1',
            'Capo Squadra - Preposto.1',
            'Soccorritore.1',
            'Soccorritore.2',
            'Supervisore Ponteggi Senior - Preposto.1',
            'Supervisore Ponteggi Junior.1',
            'Supervisore Senior - Preposto.1',
            'Supervisore Senior.1',
            'Operatore Addetto Front Office Aree Pozzo.1',
            'Coordinatore Operativo COVA - Preposto.2',
            'Tecnico Specializzato CNP/Gas Free - Preposto solo WE.2',
            'Tecnico Specializzato CNP/Gas Free - Preposto.2',
            'Front Office BO 1 - Preposto.2',
            'Front Office BO2.2',
            'Supporto Front Office ACAM - Lun/Ven (Fine settimana Site Operations Specialist/Tecnico HSE).2',
            'Operatore analisi Gas (Linee e Claus) - Preposto.2',
            'Operatore analisi Gas (Linee e Claus).2',
            'Capo Squadra - Preposto.2',
            'Soccorritore.3',
            'Soccorritore.4',
            'Supervisore Ponteggi Senior - Preposto.2',
            'Supervisore Ponteggi Junior.2',
            'Supervisore Senior - Preposto.2',
            'Supervisore Senior - Site Operations Specialist/Tecnico HSE.1',
            'Operatore Addetto Front Office Aree Pozzo.2',
            'Tecnico Specializzato CNP/Gas Free - Preposto.3',
            'Front Office BO 1 - Preposto.3',
            'Front Office BO2.3',
            'Supporto Front Office ACAM - Site Operations Specialist/Tecnico HSE.1',
            'Operatore analisi Gas (Linee e Claus) - Preposto.3',
            'Operatore analisi Gas (Linee e Claus) - Preposto.4',
            'Supervisore Senior - Preposto.3',
            'Capo Squadra - Preposto.3',
            'Soccorritore.5',
            'Soccorritore.6',
            'Delegato ai Lavori - Preposto.4',
            'Supervisore Area MISE - Preposto.1',
            'Supervisore Senior - KPI - Presso sede appaltatore.1',
            'Supervisore Senior - Preposto.4',
            'Supervisore Senior.2',
            'Supervisore Senior.3',
            'Supervisore Senior.4',
            'Supervisore Senior.5',
            'Supervisore Senior - Posti Afferenti - Preposto.1',
            'Supervisore Senior - Disposizione Coordinatore COVA - Principalmente Posti Afferenti.1',
            'Supervisore Junior.1',
            'Supervisore Junior - (principalmente LOTO/ACAM, a discrezione del coordinatore).1',
            'Supervisore Junior - (principalmente GST, a discrezione del coordinatore).1',
            'Supervisore Junior - Verifica attrezzatture/Gestione Magazzino HSE.1',
            'Ispettore Ponteggi - Preposto.1',
            'Supporto Ponteggi - Site Operations Specialist/Tecnico HSE.1',
            'Operatore Addetto Controllo Mezzi - IDL - Preposto.1',
            'Operatore Addetto Controllo Mezzi - IDL.1',
            'ICT - Preposto (orario 07:00-19:00).1',
            'ICT - Preposto (orario 19:00-07:00).1',
            'RDC  - Preposto.1',
            'RDC  - Preposto.2',
            'RDC  - Preposto.3',
            'RDC  - Preposto.4',
            'Delegato ai Lavori - Preposto.1',
            'Delegato ai Lavori - Preposto.2',
            'Delegato ai Lavori - Preposto.3',
            'Coordinatore Operativo Altri Siti DIME (ad eccezione del COVA) - Preposto.1',
            'Supervisore Senior Pisticci.1',
            'Supervisore Senior Candela.1',
            'Supervisore Senior Roseto.1',
            'Delegato ai Lavori - Centrali Minori (DEG 5) - Preposto.1',
            'Delegato ai Lavori - Centrali Minori  (Torrente Vulgano 9 ) - Preposto.1',
            'Supervisione HSE Perforzione/Workover  - CF 3 Day - Orario 07:00-19:00.1',
            'Supervisione HSE Perforzione/Workover  - CF 3 Night - Orario 19:00-07:00.1',
            'Supervisione HSE Perforzione/Workover/rigless  - MA 7 Day - Orario 07:00-19:00.1',
            'Supervisione HSE Perforzione/Workover  - Alli 4 Day - Orario 07:00-19:00.1',
            'Supervisione HSE Perforzione/Workover/rigless  - Volturino 1 Day - Orario 07:00-19:00.1',
            'Supervisione HSE Perforzione/Workover/rigless  - MAE 1 Day - Orario 07:00-19:00.1',
            'Site Operations Specialist/Tecnico HSE - a discrezione del Coordinatore Operativo COVA.1',
            'Site Operations Specialist/Tecnico HSE - a discrezione del Coordinatore Operativo COVA.2',
            'Site Operations Specialist/Tecnico HSE - a discrezione del Coordinatore Operativo COVA.3',
            'Site Operations Specialist/Tecnico HSE - a discrezione del Coordinatore Operativo COVA.4',
            'Site Operations Specialist/Tecnico HSE - a discrezione del Coordinatore Operativo COVA.5',
            'Site Operations Specialist/Tecnico HSE - a discrezione del Coordinatore Operativo COVA.6',
            'Site Operations Specialist/Tecnico HSE - RDC.1',
            'Site Operations Specialist/Tecnico HSE - a discrezione del Coordinatore Operativo COVA.7',
            'Site Operations Specialist/Tecnico HSE - a discrezione del Coordinatore Operativo COVA.8',
            'Site Operations Specialist/Tecnico HSE - a discrezione del Coordinatore Operativo COVA.9',
            'Site Operations Specialist/Tecnico HSE - a discrezione del Coordinatore Operativo COVA.10',
            'Site Operations Specialist/Tecnico HSE - a discrezione del Coordinatore Operativo COVA.11',
            'Site Operations Specialist/Tecnico HSE - a discrezione del Coordinatore Operativo COVA.12',
            'Site Operations Specialist/Tecnico HSE - a discrezione del Coordinatore Operativo COVA.13',
            'Site Operations Specialist/Tecnico HSE - a discrezione del Coordinatore Operativo COVA.14',
            'Site Operations Specialist/Tecnico HSE - a discrezione del Coordinatore Operativo COVA.15',
            'Site Operations Specialist/Tecnico HSE - a discrezione del Coordinatore Operativo COVA - Front Office.1',
            'Site Operations Specialist/Tecnico HSE - a discrezione del Coordinatore Operativo COVA.16',
            'Site Operations Specialist/Tecnico HSE - RDC.2',
            'Site Operations Specialist/Tecnico HSE - a discrezione del referente Delegati e front office pozzi.1',
            'Site Operations Specialist/Tecnico HSE - a discrezione del referente Delegati e front office pozzi.2',
            'Site Operations Specialist/Tecnico HSE - a discrezione del Coordinatore Generale.1',
            'Formazione.1',
            'Formazione.2',
            'Formazione.3',
            'Formazione.4',
            'Formazione.5',
            'Formazione.6',
            'Ferie.1',
            'Ferie.2',
            'Ferie.3',
            'Ferie.4',
            'Ferie.5',
            'Ferie.6',
            'Ferie.7',
            'Ferie.8',
            'Ferie.9',
            'Ferie.10',
            'Ferie.11',
            'Ferie.12',
            'Ferie.13',
            'Ferie.14',
            'Ferie.15',
            'Ferie.16',
            'Ferie.17',
            'Ferie.18',
            'Ferie.19',
            'Ferie.20',
            'Ferie.21',
            'Ferie.22',
            'Permessi.23',
            'Permessi.24',
            'Permessi.25',
            'Permessi.26',
            'Permessi.27',
            'Permessi.28',
            'Permessi.29',
            'Congedo.1',
            'Congedo.2',
            'Congedo.3',
            'Congedo.4',
            'Congedo.5',
            'Congedo.6',
            'Congedo.7',
            'Congedo.8',
            'Congedo.9',
            'Congedo.10',
            'Congedo Matrimoniale.1',
            'Congedo Matrimoniale.2',
            'Permesso 104.1',
            'Permesso 104.2',
            'Malattia.1',
            'Malattia.2',
            'Malattia.3',
            'Malattia.4',
            'Malattia.5',
            'Assenza.1',
            'Assenza.2',
            'Assenza.3',
            'Permesso Sindacale.1',
            'Permesso Sindacale.2',
            'Permesso Sindacale.3',
            'Permesso Sindacale.4',
            'Permesso Sindacale.5',
            'Sciopero.1',
            'Sciopero.2',
            'Formazione.7',
            'Formazione.8'
        ]

        for name in professions:
            obj, created = Profession.objects.get_or_create(name=name)
            if created:
                self.stdout.write(self.style.SUCCESS(f"Aggiunta professione: {name}"))
            else:
                self.stdout.write(f"Già presente: {name}")
